version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - fintech-network

  flink-jobmanager:
    image: apache/flink:1.18.1
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    networks:
      - fintech-network

  flink-taskmanager:
    image: apache/flink:1.18.1
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - fintech-network

  data-producer:
    build: ./data-producer
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    networks:
      - fintech-network

  stream-processor:
    build: ./stream-processor
    env_file:
      - ./.env
    depends_on:
      - flink-jobmanager
      - data-producer
    networks:
      - fintech-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fintech_data}
      POSTGRES_USER: ${POSTGRES_USER:-fintech_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fintech_pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fintech-network

  superset:
    image: apache/superset:3.0.1
    ports:
      - "8080:8088"
    depends_on:
      - postgres
    environment:
      SUPERSET_SECRET_KEY: your-secret-key-here
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset/dashboard_export.json:/app/dashboard_export.json
    networks:
      - fintech-network

networks:
  fintech-network:
    driver: bridge

volumes:
  postgres-data: